// <auto-generated />
using System;
using BudgetApp.DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BudgetApp.DAL.Migrations
{
    [DbContext(typeof(BudgetContext))]
    [Migration("20260806144953_updateTypes")]
    partial class updateTypes
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BudgetApp.DAL.BudgetPriority", b =>
                {
                    b.Property<byte>("PriorityId")
                        .HasColumnType("tinyint")
                        .HasColumnName("PriorityID");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("PriorityId")
                        .HasName("PK_PriorityID");

                    b.ToTable("BudgetPriorities");
                });

            modelBuilder.Entity("BudgetApp.DAL.EstablishedLink", b =>
                {
                    b.Property<int>("LinkId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("LinkID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LinkId"));

                    b.Property<int>("BucketId")
                        .HasColumnType("int")
                        .HasColumnName("BucketID");

                    b.Property<string>("Category")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ContainsText")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("LinkId")
                        .HasName("PK_LinkID");

                    b.HasIndex("BucketId");

                    b.ToTable("EstablishedLinks");
                });

            modelBuilder.Entity("BudgetApp.DAL.MonthlyBudget", b =>
                {
                    b.Property<int>("MonthlyBudgetId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MonthlyBudgetID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MonthlyBudgetId"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(19, 2)");

                    b.Property<int>("BucketId")
                        .HasColumnType("int")
                        .HasColumnName("BucketID");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nchar(3)")
                        .IsFixedLength();

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("date");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.HasKey("MonthlyBudgetId")
                        .HasName("PK_MonthlyBudgetID");

                    b.HasIndex("BucketId");

                    b.ToTable("MonthlyBudget", (string)null);
                });

            modelBuilder.Entity("BudgetApp.DAL.SpendingBucket", b =>
                {
                    b.Property<int>("BucketId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("BucketID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BucketId"));

                    b.Property<string>("BucketLabel")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<byte>("DefaultPriority")
                        .HasColumnType("tinyint");

                    b.Property<short>("DisplayOrder")
                        .HasColumnType("smallint");

                    b.HasKey("BucketId")
                        .HasName("PK_BucketID");

                    b.HasIndex("DefaultPriority");

                    b.ToTable("SpendingBuckets");
                });

            modelBuilder.Entity("BudgetApp.DAL.Transaction", b =>
                {
                    b.Property<int>("TransactionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("TransactionID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TransactionId"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(19, 2)");

                    b.Property<int?>("BucketId")
                        .HasColumnType("int")
                        .HasColumnName("BucketID");

                    b.Property<string>("Card")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<string>("Category")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nchar(3)")
                        .IsFixedLength();

                    b.Property<bool>("Debit")
                        .HasColumnType("bit");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<byte?>("Priority")
                        .HasColumnType("tinyint");

                    b.Property<string>("Reference")
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<DateOnly>("TransactionDate")
                        .HasColumnType("date");

                    b.HasKey("TransactionId")
                        .HasName("PK_TransactionID");

                    b.HasIndex("BucketId");

                    b.ToTable("Transactions");
                });

            modelBuilder.Entity("BudgetApp.DAL.EstablishedLink", b =>
                {
                    b.HasOne("BudgetApp.DAL.SpendingBucket", "Bucket")
                        .WithMany("EstablishedLinks")
                        .HasForeignKey("BucketId")
                        .IsRequired()
                        .HasConstraintName("FK_EstablishedLinks_SpendingBuckets");

                    b.Navigation("Bucket");
                });

            modelBuilder.Entity("BudgetApp.DAL.MonthlyBudget", b =>
                {
                    b.HasOne("BudgetApp.DAL.SpendingBucket", "Bucket")
                        .WithMany("MonthlyBudgets")
                        .HasForeignKey("BucketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_MonthlyBudget_SpendingBuckets");

                    b.Navigation("Bucket");
                });

            modelBuilder.Entity("BudgetApp.DAL.SpendingBucket", b =>
                {
                    b.HasOne("BudgetApp.DAL.BudgetPriority", "Priority")
                        .WithMany("Buckets")
                        .HasForeignKey("DefaultPriority")
                        .IsRequired()
                        .HasConstraintName("FK_SpendingBuckets_BudgetPriorities");

                    b.Navigation("Priority");
                });

            modelBuilder.Entity("BudgetApp.DAL.Transaction", b =>
                {
                    b.HasOne("BudgetApp.DAL.SpendingBucket", "Bucket")
                        .WithMany("Transactions")
                        .HasForeignKey("BucketId")
                        .HasConstraintName("FK_Transactions_SpendingBuckets");

                    b.Navigation("Bucket");
                });

            modelBuilder.Entity("BudgetApp.DAL.BudgetPriority", b =>
                {
                    b.Navigation("Buckets");
                });

            modelBuilder.Entity("BudgetApp.DAL.SpendingBucket", b =>
                {
                    b.Navigation("EstablishedLinks");

                    b.Navigation("MonthlyBudgets");

                    b.Navigation("Transactions");
                });
#pragma warning restore 612, 618
        }
    }
}
