// <auto-generated />
using System;
using BudgetApp.DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BudgetApp.DAL.Migrations
{
    [DbContext(typeof(BudgetContext))]
    partial class BudgetContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BudgetApp.DAL.CapitalOneTransaction", b =>
                {
                    b.Property<int>("CapitalOneTransactionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("CapitalOneTransactionID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CapitalOneTransactionId"));

                    b.Property<string>("Card")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("nchar(4)")
                        .IsFixedLength();

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal?>("Credit")
                        .HasColumnType("decimal(19, 2)");

                    b.Property<decimal?>("Debit")
                        .HasColumnType("decimal(19, 2)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<DateOnly>("TransactionDate")
                        .HasColumnType("date");

                    b.HasKey("CapitalOneTransactionId")
                        .HasName("PK_CapitalOneTransactionID");

                    b.ToTable("CapitalOneTransactions");
                });

            modelBuilder.Entity("BudgetApp.DAL.ChaseTransaction", b =>
                {
                    b.Property<int>("ChaseTransactionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ChaseTransactionID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ChaseTransactionId"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(19, 2)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("Details")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nchar(10)")
                        .IsFixedLength();

                    b.Property<DateOnly>("PostingDate")
                        .HasColumnType("date");

                    b.Property<string>("RefNumber")
                        .HasMaxLength(10)
                        .HasColumnType("nchar(10)")
                        .IsFixedLength();

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nchar(10)")
                        .IsFixedLength();

                    b.HasKey("ChaseTransactionId")
                        .HasName("PK_ChaseTransactionID");

                    b.ToTable("ChaseTransactions");
                });

            modelBuilder.Entity("BudgetApp.DAL.EstablishedLink", b =>
                {
                    b.Property<int>("LinkId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("LinkID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LinkId"));

                    b.Property<int>("BucketId")
                        .HasColumnType("int")
                        .HasColumnName("BucketID");

                    b.Property<string>("Category")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ContainsText")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("LinkId")
                        .HasName("PK_LinkID");

                    b.HasIndex("BucketId");

                    b.ToTable("EstablishedLinks");
                });

            modelBuilder.Entity("BudgetApp.DAL.MonthlyBudget", b =>
                {
                    b.Property<int>("MonthlyBudgetId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MonthlyBudgetID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MonthlyBudgetId"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(19, 2)");

                    b.Property<int>("BucketId")
                        .HasColumnType("int")
                        .HasColumnName("BucketID");

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("date");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.HasKey("MonthlyBudgetId")
                        .HasName("PK_MonthlyBudgetID");

                    b.HasIndex("BucketId");

                    b.ToTable("MonthlyBudget", (string)null);
                });

            modelBuilder.Entity("BudgetApp.DAL.SpendingBucket", b =>
                {
                    b.Property<int>("BucketId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("BucketID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BucketId"));

                    b.Property<string>("BucketLabel")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<byte>("DefaultPriority")
                        .HasColumnType("tinyint")
                        .HasColumnName("DefaultPriority");

                    b.Property<short>("DisplayOrder")
                        .HasColumnType("smallint")
                        .HasColumnName("DisplayOrder");

                    b.HasKey("BucketId")
                        .HasName("PK_BucketID");

                    b.ToTable("SpendingBuckets");
                });

            modelBuilder.Entity("BudgetApp.DAL.Transaction", b =>
                {
                    b.Property<int>("TransactionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("TransactionID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TransactionId"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(19, 2)");

                    b.Property<int?>("BucketId")
                        .HasColumnType("int")
                        .HasColumnName("BucketID");

                    b.Property<string>("Card")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nchar(8)")
                        .IsFixedLength();

                    b.Property<string>("Category")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("Debit")
                        .HasColumnType("bit");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<byte?>("Priority")
                        .HasColumnType("tinyint")
                        .HasColumnName("Priority");

                    b.Property<string>("Reference")
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<DateOnly>("TransactionDate")
                        .HasColumnType("date");

                    b.HasKey("TransactionId")
                        .HasName("PK_TransactionID");

                    b.HasIndex("BucketId");

                    b.ToTable("Transactions");
                });

            modelBuilder.Entity("BudgetApp.DAL.EstablishedLink", b =>
                {
                    b.HasOne("BudgetApp.DAL.SpendingBucket", "Bucket")
                        .WithMany("EstablishedLinks")
                        .HasForeignKey("BucketId")
                        .IsRequired()
                        .HasConstraintName("FK_EstablishedLinks_SpendingBuckets");

                    b.Navigation("Bucket");
                });

            modelBuilder.Entity("BudgetApp.DAL.MonthlyBudget", b =>
                {
                    b.HasOne("BudgetApp.DAL.SpendingBucket", "Bucket")
                        .WithMany("MonthlyBudgets")
                        .HasForeignKey("BucketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_MonthlyBudget_SpendingBuckets");

                    b.Navigation("Bucket");
                });

            modelBuilder.Entity("BudgetApp.DAL.Transaction", b =>
                {
                    b.HasOne("BudgetApp.DAL.SpendingBucket", "Bucket")
                        .WithMany("Transactions")
                        .HasForeignKey("BucketId")
                        .HasConstraintName("FK_Transactions_SpendingBuckets");

                    b.Navigation("Bucket");
                });

            modelBuilder.Entity("BudgetApp.DAL.SpendingBucket", b =>
                {
                    b.Navigation("EstablishedLinks");

                    b.Navigation("MonthlyBudgets");

                    b.Navigation("Transactions");
                });
#pragma warning restore 612, 618
        }
    }
}
